### ISSUE TITLE
Compile API Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/capture-receipt-capacitor#476]
As a team member, I need to compile documentation on the APIs involved in the email srape feature for the high-level system overview. This documentation will provide a comprehensive understanding of the external interfaces and integrations.

## Acceptance Criteria
- Identify all APIs integrated into the email scrape feature.
- Document the purpose and functionalities of each API.
- Specify the communication protocols and data formats used by the APIs.
- Ensure the documentation is organized and easily accessible.
- Include any authentication mechanisms or security considerations associated with the APIs.

**Comment by ricardobrg** [comment]
# TIKI Data Provider API

This API allows Data Providers to license and publish data to the platform on behalf of their end users.

## Security in Transportation
The API only allows requests with a secure connection, using HTTPS. When accessing the API, the URL should always start with https:// instead of http://. This ensures that the data is encrypted during transportation, providing an extra layer of security.

## Authentication
To access the API, the request must include a special key in the header, called a JWT token. This token contains information about the publisher and the user, ensuring secure and authorized access.

The JWT token is essential for two main reasons:

- **Authentication:** It proves that you are who you say you are (publisher and user) and that you have the right to access this API.

- **Data Integrity:** The signature ensures that the information in the token has not been tampered with during transportation. If someone tries to alter the token, the signature won't match, and the request will be rejected.

The payload of the JWT is composed of:

- Publisher ID: Unique identifier for the publisher, provided by TIKI.
- User ID: Unique identifier for the user, provided by the publisher.

Here's an example of what how the JWT token might look like:

```plaintext
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI
```

## Data License

A data license is a legal contract between a user and a business, specifically focusing on the terms under which the user's data can be monetized. It differs from general terms of service as it pertains to the user's legally-owned data (zero-party data).

A data license must be created before sending any user data to TIKI. Any user data sent without a valid data license will be discarded.

### Creating a Data License

Call this endpoint when the user agrees with the terms of the data license.

#### Endpoint

- **Method:** `POST`
- **URL:** `/licenses`

#### Request
The request parameters are sent in JSON format in the body of the request.

##### `termsURL` (String, required)
A URL with the complete terms of this agreement. Preferably in plain text. The content is permanently added to the [License Record](https://mytiki.com/reference/data-provenance#license-record).

##### `expiry` (String, optional)
The date for the agreement to automatically terminate.

#### Response

```json
{
  "licenseId": "THE_LICENSE_UNIQUE_ID"
}
```
## Send Email Receipt Data

Receipt data can be submitted as email data, including PDF attachments. The API will extract the text from the email and its attachments and convert that to receipt data that can be added to the TIKI data repository.

### Request

To submit email receipt data, you'll need to send a `multipart/form-data` request with three parameters:

1. The sender email in plain text
2. The email body in plain text
3. The email PDF attachments as files

#### Endpoint

- **Method:** `POST`
- **URL:** `/emails`

#### Request Body
```plaintext
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI

senderEmail: [plain text]
emailBody: [plain text]
attachments: [PDF files]
```

#### Example Request
```bash
curl -X POST \
  -H "Content-Type: multipart/form-data" \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI" \
  -F "senderEmail=receipt@seller.com" \
  -F "emailBody=Thank you for your purchase!" \
  -F "attachments=@receipt1.pdf" \
  -F "attachments=@receipt2.pdf" \
  https://api.mytiki.com/emails
```

### Response
The request returns the id of the request since the PDF processing may take some time to complete depending on the attachments' size. This can be used later to query the result of the request.

```json
{
  "requestId": "THE_REQUEST_UNIQUE_ID"
}
```
